tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "coreutils"
brew "openssl@1.1"
brew "asdf"
brew "python@3.9"
brew "autojump"
brew "bat"
brew "curl"
brew "docker-machine"
brew "docker-machine-nfs"
brew "fd"
brew "git"
brew "git-ftp"
brew "libffi"
brew "nghttp2"
brew "unbound"
brew "gnupg"
brew "mas"
brew "mysql-client@5.7"
brew "neovim"
brew "watch"
brew "wimlib"
brew "zola"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "datagrip"
cask "docker"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "transmission"
cask "visual-studio-code"
mas "1Blocker", id: 1107421413
mas "Cinebench", id: 1438772273
mas "Disk Speed Test", id: 425264550
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Xcode", id: 497799835
