tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
brew "bat"
brew "git"
brew "gnupg"
brew "mas"
brew "zsh"
cask "docker"
cask "macvim"
cask "psequel"
cask "sequel-pro"
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
